pipeline {
    agent any

  parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }


  environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

  stages {
      stage("Initial cleanup") {
          steps {
            dir("${WORKSPACE}") {
              deleteDir()
            }
          }
        }

      stage('Checkout SCM') {
         steps{
            git branch: 'main', url: 'https://github.com/rxneyo/ansible-config-mgt.git'
         }
       }

      stage('Prepare Ansible For Execution') {
        steps {
          sh 'echo ${WORKSPACE}' 
          sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'  
        }
     }

      stage('Run Ansible playbook') {
    steps {
        script {
            def ansibleExecutable = "/usr/bin/ansible/ansible-playbook"
            withEnv(["PATH+ANSIBLE=${ansibleExecutable}"]) {
                sh "ansible-playbook playbooks/site.yml -i inventory/dev -b --become-user root --private-key /var/lib/jenkins/workspace/ansible-config-mgt_main/ssh39098367711967853.key -u ec2-user"
            }
        }
    }
}




      stage('Clean Workspace after build') {
        steps{
          cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
        }
      }
   }

}