---
- hosts: all
  name: Include dynamic variables
  tasks:
    - include: ../static-assignments/common.yml
    - include_vars: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: webservers
  name: Webserver assignment
  tasks:
    - include: ../static-assignments/webservers.yml

- hosts: lb
  name: Loadbalancers assignment
  tasks:
    - include: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required